blank_issues_enabled: false
contact_links:
  - name: In case of any doubt? Kindly initiate discussion here:
    url: https://github.com/ant-media/Ant-Media-Server/discussions
    about: Please ask and answer questions at Github Discussion.
